### ISSUE TITLE
Error in fitting data

### ISSUE THREAD

**Issue by ghost** [grburgess/gbm_kitty#1]
Hello, Sir.

The following error occurs when I use gbm_kitty module to fit GBM data. 
`(base)jason@DESKTOP-U2B4NIQ:~$ source activate threeML
(threeML) jason@DESKTOP-U2B4NIQ:~$ get_grb_analysis --grb GRB120227725
Traceback (most recent call last):
  File "/home/jason/.conda/envs/threeML/bin/get_grb_analysis", line 33, in <module>
    sys.exit(load_entry_point('gbm-kitty==0+unknown', 'console_scripts', 'get_grb_analysis')())
  File "/home/jason/.conda/envs/threeML/bin/get_grb_analysis", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jason/.conda/envs/threeML/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/home/jason/.conda/envs/threeML/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gbm_kitty.scripts'`

I hope you can help me solve this problem, thank you!

**Comment by grburgess** [comment]
Hello, this error seems strange. Can you please format the issue so that it is easier to read?

**Comment by ghost** [comment]
OK, I installed the `grb_kitty` module in the threeML environment and I'm using `pip list` to see if it is installed and it clearly shows that it is.  I'll try your example on Github and see if it works.but the following list of errors occurred.

  Traceback (most recent call last):
  File "/home/jason/.conda/envs/threeML/bin/get_grb_analysis", line 33, in <module>
   sys.exit(load_entry_point('gbm-kitty==0+unknown', 'console_scripts', 'get_grb_analysis')())
  File "/home/jason/.conda/envs/threeML/bin/get_grb_analysis", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jason/.conda/envs/threeML/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in 
 load
    module = import_module(match.group('module'))
  File "/home/jason/.conda/envs/threeML/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'gbm_kitty.scripts'
